# Generated by Django 5.1.6 on 2025-02-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
