# Generated by Django 5.1.6 on 2025-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='쿠키'),
        ),
    ]
