# Generated by Django 5.1.6 on 2025-02-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_kakaouser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kakaouser',
            old_name='birth',
            new_name='birthdate',
        ),
    ]
