# Generated by Django 5.1.6 on 2025-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_birth_kakaouser_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KakaoUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='kakao_profile_picture',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
