# Generated by Django 5.1.6 on 2025-02-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_kakaouser_customuser_kakao_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='kakao_profile_picture',
        ),
    ]
