services:
  django:
    build: ./cook
    container_name: cookit_django
    restart: always
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - fastapi

  fastapi:
    build: ./fast_api
    container_name: cookit_fastapi
    restart: always
    volumes:
      - ./media:/app/media
    ports:
      - "9000:9000"
    env_file:
      - .env