# Generated by Django 5.1.6 on 2025-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
