# Generated by Django 5.1.6 on 2025-03-04 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeRecipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
                ('img', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('ingredients_list', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='FunsRecipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
                ('img', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fun_menu',
            },
        ),
        migrations.CreateModel(
            name='ManRecipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('recipe', models.TextField()),
                ('img', models.URLField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('video', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processed_data',
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('tag', '태그'), ('voice', '음성')], default='text', max_length=10)),
                ('question_content', models.TextField()),
                ('response_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecommendations',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_menu_id', models.IntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chats')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryChat',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
                ('response_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
