# Generated by Django 5.1.6 on 2025-03-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('tag', 'Tag'), ('voice', 'Voice')], max_length=10)),
                ('question_content', models.TextField()),
                ('response_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.users')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecommendations',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('ManRecipes', 'Man Recipes'), ('FridgeRecipes', 'Fridge Recipes'), ('FunsRecipes', 'Funs Recipes')], max_length=20)),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryChat',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserSelectedMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('source', models.CharField(choices=[('ManRecipes', 'Man Recipes'), ('FridgeRecipes', 'Fridge Recipes'), ('FunsRecipes', 'Funs Recipes')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
        ),
    ]
