# Generated by Django 5.1.6 on 2025-03-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
