# Generated by Django 5.1.6 on 2025-03-04 02:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=50, unique=True, verbose_name='로그인 ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='이메일')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='별명')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('points', models.PositiveIntegerField(default=200, verbose_name='쿠키')),
                ('provider', models.CharField(choices=[('local', 'Local'), ('kakao', 'Kakao')], default='local', max_length=10, verbose_name='로그인 제공자')),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='소셜 로그인 ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20, verbose_name='회원 상태')),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='프로필 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='정보 수정일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', '회원가입'), ('reset_password', '비밀번호 재설정')], max_length=20)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 3, 4, 2, 26, 18, 379139, tzinfo=datetime.timezone.utc))),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', '적립'), ('spend', '사용')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
