# Generated by Django 5.1.6 on 2025-03-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='인증 코드'),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='인증 코드 만료 시간'),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
