# Generated by Django 5.1.6 on 2025-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_users_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=False, verbose_name='이름'),
        ),
    ]
