# Generated by Django 5.1.6 on 2025-03-12 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historychat',
            name='messages',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historychat',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historychat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='historychat',
            name='title',
            field=models.CharField(default='새로운 대화', max_length=255),
        ),
    ]
