# Generated by Django 5.1.6 on 2025-03-05 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.userselectedmenus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.userreviews')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('like_type', models.CharField(choices=[('review_like', 'Review Like'), ('comment', 'Comment')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.userreviews')),
            ],
        ),
    ]
