# Generated by Django 5.1.6 on 2025-03-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomments',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='reviewcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.reviewcomments'),
        ),
    ]
