# Generated by Django 5.1.6 on 2025-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_reviewcomments_parent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomments',
            name='parent',
        ),
        migrations.AddField(
            model_name='reviewcomments',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
